services:
  mongo:
    image: mongo:latest
    environment:
      -MONGO_INITDB_DATABASE: mydatabase
      -MONGO_INITDB_ROOT_USERNAME: root
      -MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
    - mongo-data:/data/db

  mylibrarybe:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongo:27017/mydatabase?authSource=admin
    ports:
    - "8081:8080"
    depends_on:
    - mongo

volumes:
  mongo-data: